wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.16.6
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1714202583.0
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.10.10
      5: 0.16.6
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
